wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1647492087
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      - 16
      4: 3.9.7
      5: 0.12.11
      8:
      - 5
lr:
  desc: null
  value: 0.02
