wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1647497066
    t:
      1:
      - 1
      3:
      - 16
      4: 3.9.7
      5: 0.12.11
      8:
      - 5
dataset_size:
  desc: null
  value: 10000
depth:
  desc: null
  value: 3
lr:
  desc: null
  value: 1
steps:
  desc: null
  value: 1000
width:
  desc: null
  value: 100
