wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1647578095
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      - 16
      4: 3.9.7
      5: 0.12.11
      8:
      - 5
dataset_size:
  desc: null
  value: 10000
depth:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.2
nnsym:
  desc: null
  value: false
steps:
  desc: null
  value: 1000
svdsym:
  desc: null
  value: true
width:
  desc: null
  value: 100
